net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_congestion_control = bbr

# This only works on the linux-next kernel branch (6.20/7.0) as of 1/31/2026
net.core.default_qdisc = cake_mq

net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_ecn = 1
net.ipv4.tcp_adv_win_scale = 1
net.core.busy_poll = 50
net.core.busy_read = 50
net.core.netdev_budget = 600
kernel.printk = 3 3 3 3
kernel.printk_devkmsg = off
kernel.panic = 10
kernel.core_pattern = |/bin/false
kernel.core_pipe_limit = 0
kernel.timer_migration = 0
kernel.perf_cpu_time_max_percent = 5
kernel.sched_autogroup_enabled = 0
kernel.nmi_watchdog = 0
kernel.numa_balancing = 0
kernel.split_lock_mitigate = 0
vm.vfs_cache_pressure = 10
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 500
vm.swappiness = 125
vm.compaction_proactiveness = 60
vm.stat_interval = 10
vm.page_lock_unfairness = 1
vm.page-cluster = 0
vm.unprivileged_userfaultfd = 1
vm.extfrag_threshold = 500
vm.zone_reclaim_mode = 0
fs.lease-break-time = 10
fs.suid_dumpable = 0
